# Generated by Django 5.1.1 on 2025-01-19 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_invoice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hosted_invoice_url', models.CharField(max_length=9863)),
                ('invoice_pdf', models.CharField(max_length=9863)),
                ('invoice_id', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('stripe_subscription_id', models.CharField(max_length=255)),
                ('customer_id', models.CharField(max_length=255)),
                ('subscribe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subscribe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
